//
// CurrencyCoreAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class CurrencyCoreAPI {

    /**
     AI
     
     - parameter q: (query) A natural-language question, e.g. \&quot;Convert 50 euro to indian rupees\&quot; or \&quot;What&#39;s the USD to EUR rate today?\&quot;. 
     - returns: AiResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func ai(q: String) async throws -> AiResponse {
        return try await aiWithRequestBuilder(q: q).execute().body
    }

    /**
     AI
     - GET /ai
     - Ask a natural-language currency question; the model answers using live rates.
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter q: (query) A natural-language question, e.g. \&quot;Convert 50 euro to indian rupees\&quot; or \&quot;What&#39;s the USD to EUR rate today?\&quot;. 
     - returns: RequestBuilder<AiResponse> 
     */
    open class func aiWithRequestBuilder(q: String) -> RequestBuilder<AiResponse> {
        let localVariablePath = "/ai"
        let localVariableURLString = CurrencyCoreSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "q": (wrappedValue: q.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AiResponse>.Type = CurrencyCoreSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Convert
     
     - parameter from: (query) Source currency (ISO 4217), e.g. USD. For PPP (ppp&#x3D;true) pair it with a country as CUR:COUNTRY, e.g. USD:USA. 
     - parameter to: (query) One or more target currencies, comma-separated, e.g. EUR,INR (max 25). For PPP use CUR:COUNTRY pairs, e.g. EUR:DEU,INR:IND. 
     - parameter amount: (query) Amount to convert. Optional, defaults to 1 (so each result equals the rate). (optional)
     - parameter ppp: (query) When true, apply a PPP adjustment. Every currency must then carry a country code. (optional)
     - parameter date: (query) Rate date in YYYY-MM-DD (UTC). Must not be in the future. Defaults to latest. (optional)
     - returns: ConvertResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func convert(from: String, to: String, amount: Double? = nil, ppp: Bool? = nil, date: String? = nil) async throws -> ConvertResponse {
        return try await convertWithRequestBuilder(from: from, to: to, amount: amount, ppp: ppp, date: date).execute().body
    }

    /**
     Convert
     - GET /convert
     - Convert an amount between currencies, optionally PPP-adjusted.
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter from: (query) Source currency (ISO 4217), e.g. USD. For PPP (ppp&#x3D;true) pair it with a country as CUR:COUNTRY, e.g. USD:USA. 
     - parameter to: (query) One or more target currencies, comma-separated, e.g. EUR,INR (max 25). For PPP use CUR:COUNTRY pairs, e.g. EUR:DEU,INR:IND. 
     - parameter amount: (query) Amount to convert. Optional, defaults to 1 (so each result equals the rate). (optional)
     - parameter ppp: (query) When true, apply a PPP adjustment. Every currency must then carry a country code. (optional)
     - parameter date: (query) Rate date in YYYY-MM-DD (UTC). Must not be in the future. Defaults to latest. (optional)
     - returns: RequestBuilder<ConvertResponse> 
     */
    open class func convertWithRequestBuilder(from: String, to: String, amount: Double? = nil, ppp: Bool? = nil, date: String? = nil) -> RequestBuilder<ConvertResponse> {
        let localVariablePath = "/convert"
        let localVariableURLString = CurrencyCoreSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "from": (wrappedValue: from.encodeToJSON(), isExplode: true),
            "to": (wrappedValue: to.encodeToJSON(), isExplode: true),
            "amount": (wrappedValue: amount?.encodeToJSON(), isExplode: true),
            "ppp": (wrappedValue: ppp?.encodeToJSON(), isExplode: true),
            "date": (wrappedValue: date?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ConvertResponse>.Type = CurrencyCoreSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Correlation
     
     - parameter currencies: (query) Comma-separated currencies to correlate with &#x60;base&#x60;, e.g. GBP,CHF,SEK. 
     - parameter base: (query) Reference currency to correlate against (3-letter ISO 4217). Defaults to USD (a non-USD base is more meaningful). (optional)
     - parameter from: (query) Window start YYYY-MM-DD (UTC). Defaults to 365 days before &#x60;to&#x60;. (optional)
     - parameter to: (query) Window end YYYY-MM-DD (UTC). Defaults to today. (optional)
     - returns: CorrelationResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func correlation(currencies: String, base: String? = nil, from: String? = nil, to: String? = nil) async throws -> CorrelationResponse {
        return try await correlationWithRequestBuilder(currencies: currencies, base: base, from: from, to: to).execute().body
    }

    /**
     Correlation
     - GET /correlation
     - Correlation of each currency's daily returns with a base currency's, over a window. Growth plan or higher.
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter currencies: (query) Comma-separated currencies to correlate with &#x60;base&#x60;, e.g. GBP,CHF,SEK. 
     - parameter base: (query) Reference currency to correlate against (3-letter ISO 4217). Defaults to USD (a non-USD base is more meaningful). (optional)
     - parameter from: (query) Window start YYYY-MM-DD (UTC). Defaults to 365 days before &#x60;to&#x60;. (optional)
     - parameter to: (query) Window end YYYY-MM-DD (UTC). Defaults to today. (optional)
     - returns: RequestBuilder<CorrelationResponse> 
     */
    open class func correlationWithRequestBuilder(currencies: String, base: String? = nil, from: String? = nil, to: String? = nil) -> RequestBuilder<CorrelationResponse> {
        let localVariablePath = "/correlation"
        let localVariableURLString = CurrencyCoreSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "base": (wrappedValue: base?.encodeToJSON(), isExplode: true),
            "currencies": (wrappedValue: currencies.encodeToJSON(), isExplode: true),
            "from": (wrappedValue: from?.encodeToJSON(), isExplode: true),
            "to": (wrappedValue: to?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CorrelationResponse>.Type = CurrencyCoreSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Countries
     
     - returns: [CountriesResponseInner]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func countries() async throws -> [CountriesResponseInner] {
        return try await countriesWithRequestBuilder().execute().body
    }

    /**
     Countries
     - GET /countries
     - The supported countries and their official currencies. Public, no key needed.
     - returns: RequestBuilder<[CountriesResponseInner]> 
     */
    open class func countriesWithRequestBuilder() -> RequestBuilder<[CountriesResponseInner]> {
        let localVariablePath = "/countries"
        let localVariableURLString = CurrencyCoreSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[CountriesResponseInner]>.Type = CurrencyCoreSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Currencies
     
     - returns: [CurrenciesResponseInner]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func currencies() async throws -> [CurrenciesResponseInner] {
        return try await currenciesWithRequestBuilder().execute().body
    }

    /**
     Currencies
     - GET /currencies
     - The full list of supported ISO 4217 currencies. Use it to resolve a name or symbol to its code, or to check whether a currency is supported (so a missing one fails clearly, not silently). Public, no key needed.
     - returns: RequestBuilder<[CurrenciesResponseInner]> 
     */
    open class func currenciesWithRequestBuilder() -> RequestBuilder<[CurrenciesResponseInner]> {
        let localVariablePath = "/currencies"
        let localVariableURLString = CurrencyCoreSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[CurrenciesResponseInner]>.Type = CurrencyCoreSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Drawdown
     
     - parameter currency: (query) Currency to measure (3-letter ISO 4217), or a comma-separated list. OMIT to RANK the liquid set by drawdown. (optional)
     - parameter base: (query) Base currency to measure against (3-letter ISO 4217). Defaults to USD. (optional)
     - parameter from: (query) Window start YYYY-MM-DD (UTC). Defaults to 365 days before &#x60;to&#x60;. (optional)
     - parameter to: (query) Window end YYYY-MM-DD (UTC). Defaults to today. (optional)
     - parameter sort: (query) Ranking direction: deepest (largest decline first, default) or recovery (fastest recovery first). (optional)
     - parameter universe: (query) Ranking universe: liquid (default) or majors. (optional)
     - parameter limit: (query) Ranking: how many to return (default 10, max 50). (optional)
     - returns: DrawdownResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func drawdown(currency: String? = nil, base: String? = nil, from: String? = nil, to: String? = nil, sort: String? = nil, universe: String? = nil, limit: Double? = nil) async throws -> DrawdownResponse {
        return try await drawdownWithRequestBuilder(currency: currency, base: base, from: from, to: to, sort: sort, universe: universe, limit: limit).execute().body
    }

    /**
     Drawdown
     - GET /drawdown
     - Maximum peak-to-trough decline vs a base (with peak/trough/recovery), or a drawdown ranking. Growth plan or higher.
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter currency: (query) Currency to measure (3-letter ISO 4217), or a comma-separated list. OMIT to RANK the liquid set by drawdown. (optional)
     - parameter base: (query) Base currency to measure against (3-letter ISO 4217). Defaults to USD. (optional)
     - parameter from: (query) Window start YYYY-MM-DD (UTC). Defaults to 365 days before &#x60;to&#x60;. (optional)
     - parameter to: (query) Window end YYYY-MM-DD (UTC). Defaults to today. (optional)
     - parameter sort: (query) Ranking direction: deepest (largest decline first, default) or recovery (fastest recovery first). (optional)
     - parameter universe: (query) Ranking universe: liquid (default) or majors. (optional)
     - parameter limit: (query) Ranking: how many to return (default 10, max 50). (optional)
     - returns: RequestBuilder<DrawdownResponse> 
     */
    open class func drawdownWithRequestBuilder(currency: String? = nil, base: String? = nil, from: String? = nil, to: String? = nil, sort: String? = nil, universe: String? = nil, limit: Double? = nil) -> RequestBuilder<DrawdownResponse> {
        let localVariablePath = "/drawdown"
        let localVariableURLString = CurrencyCoreSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "currency": (wrappedValue: currency?.encodeToJSON(), isExplode: true),
            "base": (wrappedValue: base?.encodeToJSON(), isExplode: true),
            "from": (wrappedValue: from?.encodeToJSON(), isExplode: true),
            "to": (wrappedValue: to?.encodeToJSON(), isExplode: true),
            "sort": (wrappedValue: sort?.encodeToJSON(), isExplode: true),
            "universe": (wrappedValue: universe?.encodeToJSON(), isExplode: true),
            "limit": (wrappedValue: limit?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<DrawdownResponse>.Type = CurrencyCoreSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     History
     
     - parameter currency: (query) The currency whose history to fetch (3-letter ISO 4217), e.g. INR. One currency per call. 
     - parameter from: (query) Start date YYYY-MM-DD (UTC). Defaults to 7 days before &#x60;to&#x60;. (optional)
     - parameter to: (query) End date YYYY-MM-DD (UTC). Defaults to today; a future date clamps to today. (optional)
     - parameter base: (query) Base currency the rates are expressed against (3-letter ISO 4217). Defaults to USD. (optional)
     - parameter interval: (query) Aggregation: daily (default), weekly, monthly, or yearly. Coarser intervals average the daily rates per bucket (weekly key &#x3D; the week&#39;s Monday, monthly &#x3D; YYYY-MM, yearly &#x3D; YYYY). (optional)
     - returns: HistoryResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func history(currency: String, from: String? = nil, to: String? = nil, base: String? = nil, interval: String? = nil) async throws -> HistoryResponse {
        return try await historyWithRequestBuilder(currency: currency, from: from, to: to, base: base, interval: interval).execute().body
    }

    /**
     History
     - GET /history
     - A single currency's daily rate time series over a date range. Growth plan or higher.
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter currency: (query) The currency whose history to fetch (3-letter ISO 4217), e.g. INR. One currency per call. 
     - parameter from: (query) Start date YYYY-MM-DD (UTC). Defaults to 7 days before &#x60;to&#x60;. (optional)
     - parameter to: (query) End date YYYY-MM-DD (UTC). Defaults to today; a future date clamps to today. (optional)
     - parameter base: (query) Base currency the rates are expressed against (3-letter ISO 4217). Defaults to USD. (optional)
     - parameter interval: (query) Aggregation: daily (default), weekly, monthly, or yearly. Coarser intervals average the daily rates per bucket (weekly key &#x3D; the week&#39;s Monday, monthly &#x3D; YYYY-MM, yearly &#x3D; YYYY). (optional)
     - returns: RequestBuilder<HistoryResponse> 
     */
    open class func historyWithRequestBuilder(currency: String, from: String? = nil, to: String? = nil, base: String? = nil, interval: String? = nil) -> RequestBuilder<HistoryResponse> {
        let localVariablePath = "/history"
        let localVariableURLString = CurrencyCoreSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "currency": (wrappedValue: currency.encodeToJSON(), isExplode: true),
            "from": (wrappedValue: from?.encodeToJSON(), isExplode: true),
            "to": (wrappedValue: to?.encodeToJSON(), isExplode: true),
            "base": (wrappedValue: base?.encodeToJSON(), isExplode: true),
            "interval": (wrappedValue: interval?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<HistoryResponse>.Type = CurrencyCoreSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     History analysis
     
     - parameter base: (query) Currency everything is measured against (3-letter ISO 4217). Defaults to USD. (optional)
     - parameter currencies: (query) Comma-separated currencies to compare, e.g. GBP,EUR,AED. OMIT to rank ALL currencies vs base (&#39;movers&#39; mode). (optional)
     - parameter from: (query) Window start YYYY-MM-DD (UTC). Defaults to 20 years (2 decades) before &#x60;to&#x60;. See &#x60;period&#x60; for a shorthand. (optional)
     - parameter to: (query) Window end YYYY-MM-DD (UTC). Defaults to today; a future date clamps to today. (optional)
     - parameter period: (query) Relative window shorthand for &#x60;from&#x60;: e.g. 10y, 6m, 30d, ytd, max. Ignored if &#x60;from&#x60; is given. (optional)
     - parameter sort: (query) Movers ranking: strengthened (default) or weakened. (optional)
     - parameter assetClass: (query) Movers universe: fiat (default, the liquid tradeable currencies), metals (XAU/XAG/XPT/XPD), or all (every currency incl. illiquid/frontier). fiat excludes metals/synthetics + illiquid frontier codes; redenomination artifacts are always dropped. (optional)
     - parameter limit: (query) Movers: how many top results to return (default 10, max 200). (optional)
     - parameter interval: (query) Attach a trend series per named currency: weekly, monthly, or yearly (compare mode only). (optional)
     - parameter stats: (query) Include min/max/avg over the window per currency. Defaults to true; pass false to skip. (optional)
     - returns: HistoryAnalysisResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func historyAnalysis(base: String? = nil, currencies: String? = nil, from: String? = nil, to: String? = nil, period: String? = nil, sort: String? = nil, assetClass: String? = nil, limit: Double? = nil, interval: String? = nil, stats: Bool? = nil) async throws -> HistoryAnalysisResponse {
        return try await historyAnalysisWithRequestBuilder(base: base, currencies: currencies, from: from, to: to, period: period, sort: sort, assetClass: assetClass, limit: limit, interval: interval, stats: stats).execute().body
    }

    /**
     History analysis
     - GET /history/analysis
     - Trends, comparisons & 'movers': % change, strength, and min/max/avg over a window. Growth plan or higher.
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter base: (query) Currency everything is measured against (3-letter ISO 4217). Defaults to USD. (optional)
     - parameter currencies: (query) Comma-separated currencies to compare, e.g. GBP,EUR,AED. OMIT to rank ALL currencies vs base (&#39;movers&#39; mode). (optional)
     - parameter from: (query) Window start YYYY-MM-DD (UTC). Defaults to 20 years (2 decades) before &#x60;to&#x60;. See &#x60;period&#x60; for a shorthand. (optional)
     - parameter to: (query) Window end YYYY-MM-DD (UTC). Defaults to today; a future date clamps to today. (optional)
     - parameter period: (query) Relative window shorthand for &#x60;from&#x60;: e.g. 10y, 6m, 30d, ytd, max. Ignored if &#x60;from&#x60; is given. (optional)
     - parameter sort: (query) Movers ranking: strengthened (default) or weakened. (optional)
     - parameter assetClass: (query) Movers universe: fiat (default, the liquid tradeable currencies), metals (XAU/XAG/XPT/XPD), or all (every currency incl. illiquid/frontier). fiat excludes metals/synthetics + illiquid frontier codes; redenomination artifacts are always dropped. (optional)
     - parameter limit: (query) Movers: how many top results to return (default 10, max 200). (optional)
     - parameter interval: (query) Attach a trend series per named currency: weekly, monthly, or yearly (compare mode only). (optional)
     - parameter stats: (query) Include min/max/avg over the window per currency. Defaults to true; pass false to skip. (optional)
     - returns: RequestBuilder<HistoryAnalysisResponse> 
     */
    open class func historyAnalysisWithRequestBuilder(base: String? = nil, currencies: String? = nil, from: String? = nil, to: String? = nil, period: String? = nil, sort: String? = nil, assetClass: String? = nil, limit: Double? = nil, interval: String? = nil, stats: Bool? = nil) -> RequestBuilder<HistoryAnalysisResponse> {
        let localVariablePath = "/history/analysis"
        let localVariableURLString = CurrencyCoreSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "base": (wrappedValue: base?.encodeToJSON(), isExplode: true),
            "currencies": (wrappedValue: currencies?.encodeToJSON(), isExplode: true),
            "from": (wrappedValue: from?.encodeToJSON(), isExplode: true),
            "to": (wrappedValue: to?.encodeToJSON(), isExplode: true),
            "period": (wrappedValue: period?.encodeToJSON(), isExplode: true),
            "sort": (wrappedValue: sort?.encodeToJSON(), isExplode: true),
            "assetClass": (wrappedValue: assetClass?.encodeToJSON(), isExplode: true),
            "limit": (wrappedValue: limit?.encodeToJSON(), isExplode: true),
            "interval": (wrappedValue: interval?.encodeToJSON(), isExplode: true),
            "stats": (wrappedValue: stats?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<HistoryAnalysisResponse>.Type = CurrencyCoreSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Mean reversion
     
     - parameter currencies: (query) Comma-separated currencies to score, e.g. EUR,GBP. OMIT to rank the liquid set. (optional)
     - parameter base: (query) Base currency to measure against (3-letter ISO 4217). Defaults to USD. (optional)
     - parameter from: (query) Window start YYYY-MM-DD (UTC). Defaults to ~2 years before &#x60;to&#x60;. (optional)
     - parameter to: (query) Window end YYYY-MM-DD (UTC). Defaults to today. (optional)
     - parameter limit: (query) How many to return (default 10, max 50). (optional)
     - returns: MeanReversionResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func meanReversion(currencies: String? = nil, base: String? = nil, from: String? = nil, to: String? = nil, limit: Double? = nil) async throws -> MeanReversionResponse {
        return try await meanReversionWithRequestBuilder(currencies: currencies, base: base, from: from, to: to, limit: limit).execute().body
    }

    /**
     Mean reversion
     - GET /mean-reversion
     - Ranks currencies by how strongly they revert to their mean (crossing frequency + reversion half-life). Growth plan or higher.
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter currencies: (query) Comma-separated currencies to score, e.g. EUR,GBP. OMIT to rank the liquid set. (optional)
     - parameter base: (query) Base currency to measure against (3-letter ISO 4217). Defaults to USD. (optional)
     - parameter from: (query) Window start YYYY-MM-DD (UTC). Defaults to ~2 years before &#x60;to&#x60;. (optional)
     - parameter to: (query) Window end YYYY-MM-DD (UTC). Defaults to today. (optional)
     - parameter limit: (query) How many to return (default 10, max 50). (optional)
     - returns: RequestBuilder<MeanReversionResponse> 
     */
    open class func meanReversionWithRequestBuilder(currencies: String? = nil, base: String? = nil, from: String? = nil, to: String? = nil, limit: Double? = nil) -> RequestBuilder<MeanReversionResponse> {
        let localVariablePath = "/mean-reversion"
        let localVariableURLString = CurrencyCoreSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "currencies": (wrappedValue: currencies?.encodeToJSON(), isExplode: true),
            "base": (wrappedValue: base?.encodeToJSON(), isExplode: true),
            "from": (wrappedValue: from?.encodeToJSON(), isExplode: true),
            "to": (wrappedValue: to?.encodeToJSON(), isExplode: true),
            "limit": (wrappedValue: limit?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MeanReversionResponse>.Type = CurrencyCoreSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     PPP analysis
     
     - parameter countries: (query) Comma-separated ISO 3166-1 alpha-3 country codes to compare, e.g. IND,DEU,USA. OMIT to rank ALL countries by PPP-factor change (&#39;movers&#39; mode). (optional)
     - parameter from: (query) Window start YEAR (e.g. 2015). Defaults to 10 years before &#x60;to&#x60;. See &#x60;period&#x60; for a shorthand. (optional)
     - parameter to: (query) Window end YEAR (e.g. 2024). Defaults to the current year. (optional)
     - parameter period: (query) Relative window shorthand for &#x60;from&#x60;: e.g. 10y, 20y, max. Ignored if &#x60;from&#x60; is given. (optional)
     - parameter sort: (query) Movers ranking: increased (PPP factor rose most, default) or decreased. (optional)
     - parameter limit: (query) Movers: how many top results to return (default 10, max 200). (optional)
     - parameter stats: (query) Include min/max/avg of the PPP factor over the window per country. Defaults to true; pass false to skip. (optional)
     - returns: PppAnalysisResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func pppAnalysis(countries: String? = nil, from: String? = nil, to: String? = nil, period: String? = nil, sort: String? = nil, limit: Double? = nil, stats: Bool? = nil) async throws -> PppAnalysisResponse {
        return try await pppAnalysisWithRequestBuilder(countries: countries, from: from, to: to, period: period, sort: sort, limit: limit, stats: stats).execute().body
    }

    /**
     PPP analysis
     - GET /ppp/analysis
     - PPP over time: how a country's purchasing-power-parity factor changed, comparing countries, or 'movers'. Growth plan or higher.
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter countries: (query) Comma-separated ISO 3166-1 alpha-3 country codes to compare, e.g. IND,DEU,USA. OMIT to rank ALL countries by PPP-factor change (&#39;movers&#39; mode). (optional)
     - parameter from: (query) Window start YEAR (e.g. 2015). Defaults to 10 years before &#x60;to&#x60;. See &#x60;period&#x60; for a shorthand. (optional)
     - parameter to: (query) Window end YEAR (e.g. 2024). Defaults to the current year. (optional)
     - parameter period: (query) Relative window shorthand for &#x60;from&#x60;: e.g. 10y, 20y, max. Ignored if &#x60;from&#x60; is given. (optional)
     - parameter sort: (query) Movers ranking: increased (PPP factor rose most, default) or decreased. (optional)
     - parameter limit: (query) Movers: how many top results to return (default 10, max 200). (optional)
     - parameter stats: (query) Include min/max/avg of the PPP factor over the window per country. Defaults to true; pass false to skip. (optional)
     - returns: RequestBuilder<PppAnalysisResponse> 
     */
    open class func pppAnalysisWithRequestBuilder(countries: String? = nil, from: String? = nil, to: String? = nil, period: String? = nil, sort: String? = nil, limit: Double? = nil, stats: Bool? = nil) -> RequestBuilder<PppAnalysisResponse> {
        let localVariablePath = "/ppp/analysis"
        let localVariableURLString = CurrencyCoreSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "countries": (wrappedValue: countries?.encodeToJSON(), isExplode: true),
            "from": (wrappedValue: from?.encodeToJSON(), isExplode: true),
            "to": (wrappedValue: to?.encodeToJSON(), isExplode: true),
            "period": (wrappedValue: period?.encodeToJSON(), isExplode: true),
            "sort": (wrappedValue: sort?.encodeToJSON(), isExplode: true),
            "limit": (wrappedValue: limit?.encodeToJSON(), isExplode: true),
            "stats": (wrappedValue: stats?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PppAnalysisResponse>.Type = CurrencyCoreSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Rates
     
     - parameter date: (query) YYYY-MM-DD. Defaults to the latest available date. (optional)
     - returns: RatesResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func rates(date: String? = nil) async throws -> RatesResponse {
        return try await ratesWithRequestBuilder(date: date).execute().body
    }

    /**
     Rates
     - GET /rates
     - The full exchange-rate snapshot for a date (USD base).
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter date: (query) YYYY-MM-DD. Defaults to the latest available date. (optional)
     - returns: RequestBuilder<RatesResponse> 
     */
    open class func ratesWithRequestBuilder(date: String? = nil) -> RequestBuilder<RatesResponse> {
        let localVariablePath = "/rates"
        let localVariableURLString = CurrencyCoreSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "date": (wrappedValue: date?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<RatesResponse>.Type = CurrencyCoreSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Rates by base
     
     - parameter base: (path) Base currency (3-letter ISO 4217), e.g. EUR. 
     - parameter date: (query) YYYY-MM-DD. Defaults to the latest available date. (optional)
     - returns: RatesByBaseResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func ratesByBase(base: String, date: String? = nil) async throws -> RatesByBaseResponse {
        return try await ratesByBaseWithRequestBuilder(base: base, date: date).execute().body
    }

    /**
     Rates by base
     - GET /rates/{base}
     - The same snapshot re-expressed against any base currency.
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter base: (path) Base currency (3-letter ISO 4217), e.g. EUR. 
     - parameter date: (query) YYYY-MM-DD. Defaults to the latest available date. (optional)
     - returns: RequestBuilder<RatesByBaseResponse> 
     */
    open class func ratesByBaseWithRequestBuilder(base: String, date: String? = nil) -> RequestBuilder<RatesByBaseResponse> {
        var localVariablePath = "/rates/{base}"
        let basePreEscape = "\(APIHelper.mapValueToPathItem(base))"
        let basePostEscape = basePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{base}", with: basePostEscape, options: .literal, range: nil)
        let localVariableURLString = CurrencyCoreSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "date": (wrappedValue: date?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<RatesByBaseResponse>.Type = CurrencyCoreSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Safe haven
     
     - parameter currencies: (query) Comma-separated currencies to score, e.g. CHF,JPY. OMIT to rank the safe-haven pool (includes gold). (optional)
     - parameter base: (query) Base currency to measure against (3-letter ISO 4217). Defaults to USD. (optional)
     - parameter from: (query) Window start YYYY-MM-DD (UTC). Defaults to 2007-01-01 (spans the 2008 crisis + COVID). (optional)
     - parameter to: (query) Window end YYYY-MM-DD (UTC). Defaults to today. (optional)
     - parameter limit: (query) How many to return (default 10, max 50). (optional)
     - returns: SafeHavenResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func safeHaven(currencies: String? = nil, base: String? = nil, from: String? = nil, to: String? = nil, limit: Double? = nil) async throws -> SafeHavenResponse {
        return try await safeHavenWithRequestBuilder(currencies: currencies, base: base, from: from, to: to, limit: limit).execute().body
    }

    /**
     Safe haven
     - GET /safe-haven
     - Ranks currencies by a composite safe-haven score (low volatility + shallow drawdown + 2008-crisis resilience). Growth plan or higher.
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter currencies: (query) Comma-separated currencies to score, e.g. CHF,JPY. OMIT to rank the safe-haven pool (includes gold). (optional)
     - parameter base: (query) Base currency to measure against (3-letter ISO 4217). Defaults to USD. (optional)
     - parameter from: (query) Window start YYYY-MM-DD (UTC). Defaults to 2007-01-01 (spans the 2008 crisis + COVID). (optional)
     - parameter to: (query) Window end YYYY-MM-DD (UTC). Defaults to today. (optional)
     - parameter limit: (query) How many to return (default 10, max 50). (optional)
     - returns: RequestBuilder<SafeHavenResponse> 
     */
    open class func safeHavenWithRequestBuilder(currencies: String? = nil, base: String? = nil, from: String? = nil, to: String? = nil, limit: Double? = nil) -> RequestBuilder<SafeHavenResponse> {
        let localVariablePath = "/safe-haven"
        let localVariableURLString = CurrencyCoreSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "currencies": (wrappedValue: currencies?.encodeToJSON(), isExplode: true),
            "base": (wrappedValue: base?.encodeToJSON(), isExplode: true),
            "from": (wrappedValue: from?.encodeToJSON(), isExplode: true),
            "to": (wrappedValue: to?.encodeToJSON(), isExplode: true),
            "limit": (wrappedValue: limit?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SafeHavenResponse>.Type = CurrencyCoreSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Volatility
     
     - parameter currency: (query) Currency to measure (3-letter ISO 4217), or a comma-separated list to compare. OMIT to RANK the liquid-currency set by stability. (optional)
     - parameter base: (query) Base currency to measure against (3-letter ISO 4217). Defaults to USD. (optional)
     - parameter from: (query) Window start YYYY-MM-DD (UTC). Defaults to 365 days before &#x60;to&#x60;. (optional)
     - parameter to: (query) Window end YYYY-MM-DD (UTC). Defaults to today; a future date clamps to today. (optional)
     - parameter sort: (query) Ranking direction: stable (least volatile first, default) or volatile. (optional)
     - parameter universe: (query) Ranking universe: liquid (default, broad set) or majors (USD/EUR/GBP/JPY/CHF/CAD/AUD/NZD). Use majors for &#39;most volatile major pair&#39;. (optional)
     - parameter limit: (query) Ranking: how many to return (default 10, max 50). (optional)
     - returns: VolatilityResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func volatility(currency: String? = nil, base: String? = nil, from: String? = nil, to: String? = nil, sort: String? = nil, universe: String? = nil, limit: Double? = nil) async throws -> VolatilityResponse {
        return try await volatilityWithRequestBuilder(currency: currency, base: base, from: from, to: to, sort: sort, universe: universe, limit: limit).execute().body
    }

    /**
     Volatility
     - GET /volatility
     - Annualized volatility of a currency vs a base, or a stability ranking of the liquid currencies. Growth plan or higher.
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter currency: (query) Currency to measure (3-letter ISO 4217), or a comma-separated list to compare. OMIT to RANK the liquid-currency set by stability. (optional)
     - parameter base: (query) Base currency to measure against (3-letter ISO 4217). Defaults to USD. (optional)
     - parameter from: (query) Window start YYYY-MM-DD (UTC). Defaults to 365 days before &#x60;to&#x60;. (optional)
     - parameter to: (query) Window end YYYY-MM-DD (UTC). Defaults to today; a future date clamps to today. (optional)
     - parameter sort: (query) Ranking direction: stable (least volatile first, default) or volatile. (optional)
     - parameter universe: (query) Ranking universe: liquid (default, broad set) or majors (USD/EUR/GBP/JPY/CHF/CAD/AUD/NZD). Use majors for &#39;most volatile major pair&#39;. (optional)
     - parameter limit: (query) Ranking: how many to return (default 10, max 50). (optional)
     - returns: RequestBuilder<VolatilityResponse> 
     */
    open class func volatilityWithRequestBuilder(currency: String? = nil, base: String? = nil, from: String? = nil, to: String? = nil, sort: String? = nil, universe: String? = nil, limit: Double? = nil) -> RequestBuilder<VolatilityResponse> {
        let localVariablePath = "/volatility"
        let localVariableURLString = CurrencyCoreSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "currency": (wrappedValue: currency?.encodeToJSON(), isExplode: true),
            "base": (wrappedValue: base?.encodeToJSON(), isExplode: true),
            "from": (wrappedValue: from?.encodeToJSON(), isExplode: true),
            "to": (wrappedValue: to?.encodeToJSON(), isExplode: true),
            "sort": (wrappedValue: sort?.encodeToJSON(), isExplode: true),
            "universe": (wrappedValue: universe?.encodeToJSON(), isExplode: true),
            "limit": (wrappedValue: limit?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<VolatilityResponse>.Type = CurrencyCoreSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
