//
// AiResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AiResponse: Codable, JSONEncodable, Hashable {

    public var query: String
    public var answer: String
    public var data: [AnyCodable]
    public var toolCalls: Double?

    public init(query: String, answer: String, data: [AnyCodable], toolCalls: Double? = nil) {
        self.query = query
        self.answer = answer
        self.data = data
        self.toolCalls = toolCalls
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case query
        case answer
        case data
        case toolCalls
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(query, forKey: .query)
        try container.encode(answer, forKey: .answer)
        try container.encode(data, forKey: .data)
        try container.encodeIfPresent(toolCalls, forKey: .toolCalls)
    }
}

