//
// ConvertResponseResultsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ConvertResponseResultsInner: Codable, JSONEncodable, Hashable {

    public var to: String
    public var toCountry: String?
    public var result: Double
    public var rate: Double
    public var ppp: ConvertResponseResultsInnerPpp?

    public init(to: String, toCountry: String? = nil, result: Double, rate: Double, ppp: ConvertResponseResultsInnerPpp? = nil) {
        self.to = to
        self.toCountry = toCountry
        self.result = result
        self.rate = rate
        self.ppp = ppp
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case to
        case toCountry
        case result
        case rate
        case ppp
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(to, forKey: .to)
        try container.encodeIfPresent(toCountry, forKey: .toCountry)
        try container.encode(result, forKey: .result)
        try container.encode(rate, forKey: .rate)
        try container.encodeIfPresent(ppp, forKey: .ppp)
    }
}

