//
// ConvertResponseResultsInnerPppAnyOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ConvertResponseResultsInnerPppAnyOf: Codable, JSONEncodable, Hashable {

    public var fromFactor: Double
    public var toFactor: Double
    public var result: Double
    public var year: Double
    public var source: String

    public init(fromFactor: Double, toFactor: Double, result: Double, year: Double, source: String) {
        self.fromFactor = fromFactor
        self.toFactor = toFactor
        self.result = result
        self.year = year
        self.source = source
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case fromFactor
        case toFactor
        case result
        case year
        case source
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(fromFactor, forKey: .fromFactor)
        try container.encode(toFactor, forKey: .toFactor)
        try container.encode(result, forKey: .result)
        try container.encode(year, forKey: .year)
        try container.encode(source, forKey: .source)
    }
}

