//
// ConvertResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ConvertResponse: Codable, JSONEncodable, Hashable {

    public var from: String
    public var fromCountry: String?
    public var amount: Double
    public var date: String
    public var requestedDate: String?
    public var asOf: [String: String]?
    public var results: [ConvertResponseResultsInner]
    public var message: String?

    public init(from: String, fromCountry: String? = nil, amount: Double, date: String, requestedDate: String? = nil, asOf: [String: String]? = nil, results: [ConvertResponseResultsInner], message: String? = nil) {
        self.from = from
        self.fromCountry = fromCountry
        self.amount = amount
        self.date = date
        self.requestedDate = requestedDate
        self.asOf = asOf
        self.results = results
        self.message = message
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case from
        case fromCountry
        case amount
        case date
        case requestedDate
        case asOf
        case results
        case message
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(from, forKey: .from)
        try container.encodeIfPresent(fromCountry, forKey: .fromCountry)
        try container.encode(amount, forKey: .amount)
        try container.encode(date, forKey: .date)
        try container.encodeIfPresent(requestedDate, forKey: .requestedDate)
        try container.encodeIfPresent(asOf, forKey: .asOf)
        try container.encode(results, forKey: .results)
        try container.encodeIfPresent(message, forKey: .message)
    }
}

