//
// CorrelationResponseResultsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CorrelationResponseResultsInner: Codable, JSONEncodable, Hashable {

    public var currency: String
    public var correlation: Double?
    public var observations: Double
    public var note: String?

    public init(currency: String, correlation: Double?, observations: Double, note: String? = nil) {
        self.currency = currency
        self.correlation = correlation
        self.observations = observations
        self.note = note
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case currency
        case correlation
        case observations
        case note
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(currency, forKey: .currency)
        try container.encode(correlation, forKey: .correlation)
        try container.encode(observations, forKey: .observations)
        try container.encodeIfPresent(note, forKey: .note)
    }
}

