//
// CorrelationResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CorrelationResponse: Codable, JSONEncodable, Hashable {

    public var base: String
    public var from: String
    public var to: String
    public var results: [CorrelationResponseResultsInner]

    public init(base: String, from: String, to: String, results: [CorrelationResponseResultsInner]) {
        self.base = base
        self.from = from
        self.to = to
        self.results = results
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case base
        case from
        case to
        case results
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(base, forKey: .base)
        try container.encode(from, forKey: .from)
        try container.encode(to, forKey: .to)
        try container.encode(results, forKey: .results)
    }
}

