//
// CountriesResponseInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CountriesResponseInner: Codable, JSONEncodable, Hashable {

    public var code: String
    public var name: String
    public var currencies: [String]?

    public init(code: String, name: String, currencies: [String]? = nil) {
        self.code = code
        self.name = name
        self.currencies = currencies
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case code
        case name
        case currencies
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(code, forKey: .code)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(currencies, forKey: .currencies)
    }
}

