//
// CurrenciesResponseInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CurrenciesResponseInner: Codable, JSONEncodable, Hashable {

    public var code: String
    public var numeric: String
    public var name: String
    public var symbol: String

    public init(code: String, numeric: String, name: String, symbol: String) {
        self.code = code
        self.numeric = numeric
        self.name = name
        self.symbol = symbol
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case code
        case numeric
        case name
        case symbol
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(code, forKey: .code)
        try container.encode(numeric, forKey: .numeric)
        try container.encode(name, forKey: .name)
        try container.encode(symbol, forKey: .symbol)
    }
}

