//
// DrawdownResponseResultsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DrawdownResponseResultsInner: Codable, JSONEncodable, Hashable {

    public var currency: String
    public var maxDrawdownPct: Double?
    public var peakDate: String?
    public var troughDate: String?
    public var recoveryDate: String?
    public var recoveryDays: Double?
    public var note: String?

    public init(currency: String, maxDrawdownPct: Double?, peakDate: String? = nil, troughDate: String? = nil, recoveryDate: String? = nil, recoveryDays: Double? = nil, note: String? = nil) {
        self.currency = currency
        self.maxDrawdownPct = maxDrawdownPct
        self.peakDate = peakDate
        self.troughDate = troughDate
        self.recoveryDate = recoveryDate
        self.recoveryDays = recoveryDays
        self.note = note
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case currency
        case maxDrawdownPct
        case peakDate
        case troughDate
        case recoveryDate
        case recoveryDays
        case note
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(currency, forKey: .currency)
        try container.encode(maxDrawdownPct, forKey: .maxDrawdownPct)
        try container.encodeIfPresent(peakDate, forKey: .peakDate)
        try container.encodeIfPresent(troughDate, forKey: .troughDate)
        try container.encodeIfPresent(recoveryDate, forKey: .recoveryDate)
        try container.encodeIfPresent(recoveryDays, forKey: .recoveryDays)
        try container.encodeIfPresent(note, forKey: .note)
    }
}

