//
// DrawdownResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DrawdownResponse: Codable, JSONEncodable, Hashable {

    public enum Mode: String, Codable, CaseIterable {
        case compare = "compare"
        case ranking = "ranking"
    }
    public enum Sort: String, Codable, CaseIterable {
        case deepest = "deepest"
        case recovery = "recovery"
    }
    public enum Universe: String, Codable, CaseIterable {
        case liquid = "liquid"
        case majors = "majors"
    }
    public var base: String
    public var from: String
    public var to: String
    public var mode: Mode
    public var sort: Sort?
    public var universe: Universe?
    public var results: [DrawdownResponseResultsInner]

    public init(base: String, from: String, to: String, mode: Mode, sort: Sort? = nil, universe: Universe? = nil, results: [DrawdownResponseResultsInner]) {
        self.base = base
        self.from = from
        self.to = to
        self.mode = mode
        self.sort = sort
        self.universe = universe
        self.results = results
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case base
        case from
        case to
        case mode
        case sort
        case universe
        case results
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(base, forKey: .base)
        try container.encode(from, forKey: .from)
        try container.encode(to, forKey: .to)
        try container.encode(mode, forKey: .mode)
        try container.encodeIfPresent(sort, forKey: .sort)
        try container.encodeIfPresent(universe, forKey: .universe)
        try container.encode(results, forKey: .results)
    }
}

