//
// HistoryAnalysisResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct HistoryAnalysisResponse: Codable, JSONEncodable, Hashable {

    public enum Mode: String, Codable, CaseIterable {
        case compare = "compare"
        case movers = "movers"
    }
    public enum Sort: String, Codable, CaseIterable {
        case strengthened = "strengthened"
        case weakened = "weakened"
    }
    public enum AssetClass: String, Codable, CaseIterable {
        case fiat = "fiat"
        case metals = "metals"
        case all = "all"
        case crypto = "crypto"
    }
    public enum Interval: String, Codable, CaseIterable {
        case daily = "daily"
        case weekly = "weekly"
        case monthly = "monthly"
        case yearly = "yearly"
    }
    public var base: String
    public var from: String
    public var to: String
    public var mode: Mode
    public var sort: Sort?
    public var assetClass: AssetClass?
    public var interval: Interval?
    public var stats: Bool
    public var results: [HistoryAnalysisResponseResultsInner]

    public init(base: String, from: String, to: String, mode: Mode, sort: Sort? = nil, assetClass: AssetClass? = nil, interval: Interval? = nil, stats: Bool, results: [HistoryAnalysisResponseResultsInner]) {
        self.base = base
        self.from = from
        self.to = to
        self.mode = mode
        self.sort = sort
        self.assetClass = assetClass
        self.interval = interval
        self.stats = stats
        self.results = results
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case base
        case from
        case to
        case mode
        case sort
        case assetClass
        case interval
        case stats
        case results
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(base, forKey: .base)
        try container.encode(from, forKey: .from)
        try container.encode(to, forKey: .to)
        try container.encode(mode, forKey: .mode)
        try container.encodeIfPresent(sort, forKey: .sort)
        try container.encodeIfPresent(assetClass, forKey: .assetClass)
        try container.encodeIfPresent(interval, forKey: .interval)
        try container.encode(stats, forKey: .stats)
        try container.encode(results, forKey: .results)
    }
}

