//
// HistoryAnalysisResponseResultsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct HistoryAnalysisResponseResultsInner: Codable, JSONEncodable, Hashable {

    public var currency: String
    public var startDate: String
    public var endDate: String
    public var startRate: Double?
    public var endRate: Double?
    public var changePct: Double?
    public var strengthenedPct: Double?
    public var stats: HistoryAnalysisResponseResultsInnerStats?
    public var series: [String: Double]?
    public var volatility: Double?
    public var note: String?

    public init(currency: String, startDate: String, endDate: String, startRate: Double?, endRate: Double?, changePct: Double?, strengthenedPct: Double?, stats: HistoryAnalysisResponseResultsInnerStats? = nil, series: [String: Double]? = nil, volatility: Double? = nil, note: String? = nil) {
        self.currency = currency
        self.startDate = startDate
        self.endDate = endDate
        self.startRate = startRate
        self.endRate = endRate
        self.changePct = changePct
        self.strengthenedPct = strengthenedPct
        self.stats = stats
        self.series = series
        self.volatility = volatility
        self.note = note
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case currency
        case startDate
        case endDate
        case startRate
        case endRate
        case changePct
        case strengthenedPct
        case stats
        case series
        case volatility
        case note
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(currency, forKey: .currency)
        try container.encode(startDate, forKey: .startDate)
        try container.encode(endDate, forKey: .endDate)
        try container.encode(startRate, forKey: .startRate)
        try container.encode(endRate, forKey: .endRate)
        try container.encode(changePct, forKey: .changePct)
        try container.encode(strengthenedPct, forKey: .strengthenedPct)
        try container.encodeIfPresent(stats, forKey: .stats)
        try container.encodeIfPresent(series, forKey: .series)
        try container.encodeIfPresent(volatility, forKey: .volatility)
        try container.encodeIfPresent(note, forKey: .note)
    }
}

