//
// HistoryAnalysisResponseResultsInnerStats.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct HistoryAnalysisResponseResultsInnerStats: Codable, JSONEncodable, Hashable {

    public var min: Double
    public var max: Double
    public var avg: Double

    public init(min: Double, max: Double, avg: Double) {
        self.min = min
        self.max = max
        self.avg = avg
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case min
        case max
        case avg
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(min, forKey: .min)
        try container.encode(max, forKey: .max)
        try container.encode(avg, forKey: .avg)
    }
}

