//
// HistoryResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct HistoryResponse: Codable, JSONEncodable, Hashable {

    public enum Interval: String, Codable, CaseIterable {
        case daily = "daily"
        case weekly = "weekly"
        case monthly = "monthly"
        case yearly = "yearly"
    }
    public var currency: String
    public var base: String
    public var interval: Interval
    public var from: String
    public var to: String
    public var rates: [String: Double]

    public init(currency: String, base: String, interval: Interval, from: String, to: String, rates: [String: Double]) {
        self.currency = currency
        self.base = base
        self.interval = interval
        self.from = from
        self.to = to
        self.rates = rates
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case currency
        case base
        case interval
        case from
        case to
        case rates
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(currency, forKey: .currency)
        try container.encode(base, forKey: .base)
        try container.encode(interval, forKey: .interval)
        try container.encode(from, forKey: .from)
        try container.encode(to, forKey: .to)
        try container.encode(rates, forKey: .rates)
    }
}

