//
// MeanReversionResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MeanReversionResponse: Codable, JSONEncodable, Hashable {

    public enum Universe: String, Codable, CaseIterable {
        case liquid = "liquid"
        case majors = "majors"
    }
    public var base: String
    public var from: String
    public var to: String
    public var universe: Universe?
    public var results: [MeanReversionResponseResultsInner]

    public init(base: String, from: String, to: String, universe: Universe? = nil, results: [MeanReversionResponseResultsInner]) {
        self.base = base
        self.from = from
        self.to = to
        self.universe = universe
        self.results = results
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case base
        case from
        case to
        case universe
        case results
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(base, forKey: .base)
        try container.encode(from, forKey: .from)
        try container.encode(to, forKey: .to)
        try container.encodeIfPresent(universe, forKey: .universe)
        try container.encode(results, forKey: .results)
    }
}

