//
// MeanReversionResponseResultsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MeanReversionResponseResultsInner: Codable, JSONEncodable, Hashable {

    public var currency: String
    public var score: Double?
    public var deviationPct: Double?
    public var reversionFrequency: Double?
    public var halfLifeDays: Double?
    public var note: String?

    public init(currency: String, score: Double?, deviationPct: Double?, reversionFrequency: Double?, halfLifeDays: Double?, note: String? = nil) {
        self.currency = currency
        self.score = score
        self.deviationPct = deviationPct
        self.reversionFrequency = reversionFrequency
        self.halfLifeDays = halfLifeDays
        self.note = note
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case currency
        case score
        case deviationPct
        case reversionFrequency
        case halfLifeDays
        case note
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(currency, forKey: .currency)
        try container.encode(score, forKey: .score)
        try container.encode(deviationPct, forKey: .deviationPct)
        try container.encode(reversionFrequency, forKey: .reversionFrequency)
        try container.encode(halfLifeDays, forKey: .halfLifeDays)
        try container.encodeIfPresent(note, forKey: .note)
    }
}

