//
// PppAnalysisResponseResultsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PppAnalysisResponseResultsInner: Codable, JSONEncodable, Hashable {

    public var country: String
    public var startYear: Double
    public var endYear: Double
    public var startFactor: Double?
    public var endFactor: Double?
    public var changePct: Double?
    public var projected: Bool
    public var stats: HistoryAnalysisResponseResultsInnerStats?
    public var series: [String: Double]?
    public var note: String?

    public init(country: String, startYear: Double, endYear: Double, startFactor: Double?, endFactor: Double?, changePct: Double?, projected: Bool, stats: HistoryAnalysisResponseResultsInnerStats? = nil, series: [String: Double]? = nil, note: String? = nil) {
        self.country = country
        self.startYear = startYear
        self.endYear = endYear
        self.startFactor = startFactor
        self.endFactor = endFactor
        self.changePct = changePct
        self.projected = projected
        self.stats = stats
        self.series = series
        self.note = note
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case country
        case startYear
        case endYear
        case startFactor
        case endFactor
        case changePct
        case projected
        case stats
        case series
        case note
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(country, forKey: .country)
        try container.encode(startYear, forKey: .startYear)
        try container.encode(endYear, forKey: .endYear)
        try container.encode(startFactor, forKey: .startFactor)
        try container.encode(endFactor, forKey: .endFactor)
        try container.encode(changePct, forKey: .changePct)
        try container.encode(projected, forKey: .projected)
        try container.encodeIfPresent(stats, forKey: .stats)
        try container.encodeIfPresent(series, forKey: .series)
        try container.encodeIfPresent(note, forKey: .note)
    }
}

