//
// PppAnalysisResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PppAnalysisResponse: Codable, JSONEncodable, Hashable {

    public enum Mode: String, Codable, CaseIterable {
        case compare = "compare"
        case movers = "movers"
    }
    public enum Sort: String, Codable, CaseIterable {
        case increased = "increased"
        case decreased = "decreased"
    }
    public var from: Double
    public var to: Double
    public var mode: Mode
    public var sort: Sort?
    public var stats: Bool
    public var results: [PppAnalysisResponseResultsInner]

    public init(from: Double, to: Double, mode: Mode, sort: Sort? = nil, stats: Bool, results: [PppAnalysisResponseResultsInner]) {
        self.from = from
        self.to = to
        self.mode = mode
        self.sort = sort
        self.stats = stats
        self.results = results
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case from
        case to
        case mode
        case sort
        case stats
        case results
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(from, forKey: .from)
        try container.encode(to, forKey: .to)
        try container.encode(mode, forKey: .mode)
        try container.encodeIfPresent(sort, forKey: .sort)
        try container.encode(stats, forKey: .stats)
        try container.encode(results, forKey: .results)
    }
}

