//
// RatesByBaseResponsePpp.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RatesByBaseResponsePpp: Codable, JSONEncodable, Hashable {

    public var base: String
    public var year: Double
    public var values: [String: Double]

    public init(base: String, year: Double, values: [String: Double]) {
        self.base = base
        self.year = year
        self.values = values
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case base
        case year
        case values
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(base, forKey: .base)
        try container.encode(year, forKey: .year)
        try container.encode(values, forKey: .values)
    }
}

