//
// RatesResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RatesResponse: Codable, JSONEncodable, Hashable {

    public enum Base: String, Codable, CaseIterable {
        case usd = "USD"
    }
    public var date: String
    public var base: Base
    public var rates: [String: Double]
    public var requestedDate: String?
    public var asOf: [String: String]?

    public init(date: String, base: Base, rates: [String: Double], requestedDate: String? = nil, asOf: [String: String]? = nil) {
        self.date = date
        self.base = base
        self.rates = rates
        self.requestedDate = requestedDate
        self.asOf = asOf
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case date
        case base
        case rates
        case requestedDate
        case asOf
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(date, forKey: .date)
        try container.encode(base, forKey: .base)
        try container.encode(rates, forKey: .rates)
        try container.encodeIfPresent(requestedDate, forKey: .requestedDate)
        try container.encodeIfPresent(asOf, forKey: .asOf)
    }
}

