//
// RatesByBaseResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RatesByBaseResponse: Codable, JSONEncodable, Hashable {

    public var base: String
    public var date: String
    public var requestedDate: String?
    public var asOf: [String: String]?
    public var rates: [String: Double]
    public var ppp: RatesByBaseResponsePpp?

    public init(base: String, date: String, requestedDate: String? = nil, asOf: [String: String]? = nil, rates: [String: Double], ppp: RatesByBaseResponsePpp? = nil) {
        self.base = base
        self.date = date
        self.requestedDate = requestedDate
        self.asOf = asOf
        self.rates = rates
        self.ppp = ppp
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case base
        case date
        case requestedDate
        case asOf
        case rates
        case ppp
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(base, forKey: .base)
        try container.encode(date, forKey: .date)
        try container.encodeIfPresent(requestedDate, forKey: .requestedDate)
        try container.encodeIfPresent(asOf, forKey: .asOf)
        try container.encode(rates, forKey: .rates)
        try container.encodeIfPresent(ppp, forKey: .ppp)
    }
}

