//
// SafeHavenResponseCrisis.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SafeHavenResponseCrisis: Codable, JSONEncodable, Hashable {

    public var label: String
    public var from: String
    public var to: String

    public init(label: String, from: String, to: String) {
        self.label = label
        self.from = from
        self.to = to
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case label
        case from
        case to
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(label, forKey: .label)
        try container.encode(from, forKey: .from)
        try container.encode(to, forKey: .to)
    }
}

