//
// SafeHavenResponseResultsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SafeHavenResponseResultsInner: Codable, JSONEncodable, Hashable {

    public var currency: String
    public var score: Double?
    public var volatility: Double?
    public var maxDrawdownPct: Double?
    public var crisisReturnPct: Double?
    public var note: String?

    public init(currency: String, score: Double?, volatility: Double?, maxDrawdownPct: Double?, crisisReturnPct: Double?, note: String? = nil) {
        self.currency = currency
        self.score = score
        self.volatility = volatility
        self.maxDrawdownPct = maxDrawdownPct
        self.crisisReturnPct = crisisReturnPct
        self.note = note
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case currency
        case score
        case volatility
        case maxDrawdownPct
        case crisisReturnPct
        case note
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(currency, forKey: .currency)
        try container.encode(score, forKey: .score)
        try container.encode(volatility, forKey: .volatility)
        try container.encode(maxDrawdownPct, forKey: .maxDrawdownPct)
        try container.encode(crisisReturnPct, forKey: .crisisReturnPct)
        try container.encodeIfPresent(note, forKey: .note)
    }
}

