//
// VolatilityResponseResultsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct VolatilityResponseResultsInner: Codable, JSONEncodable, Hashable {

    public var currency: String
    public var volatility: Double?
    public var observations: Double
    public var note: String?

    public init(currency: String, volatility: Double?, observations: Double, note: String? = nil) {
        self.currency = currency
        self.volatility = volatility
        self.observations = observations
        self.note = note
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case currency
        case volatility
        case observations
        case note
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(currency, forKey: .currency)
        try container.encode(volatility, forKey: .volatility)
        try container.encode(observations, forKey: .observations)
        try container.encodeIfPresent(note, forKey: .note)
    }
}

